# coding: utf-8

"""
    Appliance Registry API

    Store appliances with the Appliance Registry API.

    OpenAPI spec version: 0.1.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.action import Action
from .models.action_patch import ActionPatch
from .models.action_post import ActionPost
from .models.appliance import Appliance
from .models.appliance_implementation import ApplianceImplementation
from .models.appliance_implementation_patch import ApplianceImplementationPatch
from .models.appliance_implementation_post import ApplianceImplementationPost
from .models.appliance_patch import AppliancePatch
from .models.appliance_post import AppliancePost
from .models.credentials import Credentials
from .models.error import Error
from .models.script import Script
from .models.script_patch import ScriptPatch
from .models.script_post import ScriptPost
from .models.site import Site
from .models.site_patch import SitePatch
from .models.site_post import SitePost
from .models.token_resp import TokenResp
from .models.user import User

# import apis into sdk package
from .apis.actions_api import ActionsApi
from .apis.appliance_implementations_api import ApplianceImplementationsApi
from .apis.appliances_api import AppliancesApi
from .apis.scripts_api import ScriptsApi
from .apis.sites_api import SitesApi
from .apis.users_api import UsersApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
